[phases.setup]
nixPkgs = ['...', 'nodejs_20', 'bun']

[phases.install]
cmds = ['bun install --frozen-lockfile']

[phases.build]
cmds = ['bun run build']

[phases.start]
cmds = ['node .next/standalone/server.js']
